version: "3"

services:

  cfw2:
    build: ./
    networks:
      - captain-overlay-network
    container_name: cfw2
    ports:
      - "9876:9876"
    restart: unless-stopped

networks:
  captain-overlay-network:
    external: true

